$item_id = widget["Hand"].element["0001"].item.id;
if $item_id == "ITEM_0030" or $item_id == "ITEM_0029" or $item_id == "ITEM_0028" or $item_id == "ITEM_0031" or $item_id == "ITEM_0032" then
	for $number in range (1, 26) do
			$IDnumber = make4LenNum($number);
			if widget["Scaled Fish"].element[str($IDnumber)].item == null then
				widget["Scaled Fish"].element[str($IDnumber)].item = $item_id;
				break;
			end;
	end;
end;
widget["Hand"].element["0001"].item = null;